SELECT DISTINCT ?s ?o
WHERE {
  VALUES ?class {ecrm:E7_Activity mus:M28_Individual_Performance}
  ?s a ?class;
     ecrm:P14_carried_out_by ?someone ;
     ?p ?o

  FILTER (?p IN (
    ecrm:P14_carried_out_by,
    mus:U31_had_function,
    mus:U32_had_responsibility,
    mus:U1_used_medium_of_performance,
    mus:U27_performed_character
  ))
}
