DEFINE input:inference 'mus'

PREFIX keys: <http://purl.org/NET/c4dm/keys.owl#>

SELECT DISTINCT ?s ?o
FROM <http://data.doremus.org/vocabulary>
WHERE {
  VALUES ?p {keys:mode mus:U83_has_relative_key mus:U85_has_closely_related_key}
  ?s skos:inScheme <http://data.doremus.org/vocabulary/key/> ;
     ?p ?o .
}
