SELECT DISTINCT ?s  WHERE {
  ?s a efrbroo:F31_Performance;
     prov:wasDerivedFrom / prov:wasAttributedTo ?institution .

  { ?s efrbroo:R25_performed / ecrm:P165_incorporates ?expression }
  UNION { ?s efrbroo:R66_included_performed_version_of ?expression  }

  ?expression a efrbroo:F22_Self-Contained_Expression
}
GROUP BY ?s
HAVING (count(DISTINCT ?expression) > 6)
