SELECT DISTINCT ?s  WHERE {
  GRAPH ?g {
    VALUES ?concertClass { efrbroo:F31_Performance mus:M26_Foreseen_Performance }

    ?s a ?concertClass ;
      prov:wasDerivedFrom / prov:wasAttributedTo ?institution .

    { ?s efrbroo:R66_included_performed_version_of ?expression }
    UNION
    { ?s mus:U77_foresees_performing_plan / ecrm:P165_incorporates ?expression }

    ?expression a efrbroo:F22_Self-Contained_Expression
  }
}
GROUP BY ?s ?g
HAVING (count(DISTINCT ?expression) > 6)
